Add algebraic simplifier
mj3-16/minijavac pull request #93
Opened 2016-12-09 18:21 UTC by parttimenerd

2016-12-10 12:50 UTC, sherter requested changes

2016-12-10 12:50 UTC, sherter commented on src/main/java/minijava/ir/optimize/AlgebraicSimplifier.java
> +    return true;
Why are you always returning true?

2016-12-10 12:50 UTC, sherter commented on src/main/java/minijava/ir/optimize/BaseOptimizer.java
> +  protected boolean fixedPointIteration() {
Please add some documentation for the boolean return value

2016-12-10 12:50 UTC, sherter commented on src/main/java/minijava/ir/optimize/Optimizer.java
> +  boolean optimize(Graph graph);
Please add documentation for the boolean return value

2016-12-10 12:50 UTC, sherter commented on src/main/java/minijava/ir/optimize/UnreachableCodeRemover.java
> +    return true;
Isn't it possible to detect changes? Maybe `graph.getLastIdx()` or something?

2016-12-10 12:57 UTC, parttimenerd commented on src/main/java/minijava/ir/optimize/AlgebraicSimplifier.java
> +    return true;
A mistake.

2016-12-11 22:10 UTC, sgraf812 approved these changes

2016-12-12 21:54 UTC, sherter commented on src/main/java/minijava/ir/optimize/AlgebraicSimplifier.java
> +      exchange(node, subNodes.v1);
Calling this helper method `exchange` is misleading. My first thought was that you are mixing up analysis and optimization phase...

2016-12-12 21:54 UTC, sherter approved these changes

2016-12-13 13:20 UTC, merged